TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE medical_organization CASCADE;
TRUNCATE TABLE department CASCADE;
TRUNCATE TABLE patient_history CASCADE;
TRUNCATE TABLE employee_history CASCADE;
TRUNCATE TABLE talon CASCADE;

