package com.kasumov.med_ci.controller.registrar;

import com.kasumov.med_ci.util.ContextIT;
import org.hamcrest.Matchers;
import org.hamcrest.core.Is;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.context.jdbc.Sql;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class RegistrarDepartmentRestControllerIT extends ContextIT {

    @Test
    @Sql(executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD,
            value = "/scripts/controller/registrar/registrar_department_rest_controller/getAllDepartmentsAndDoctorsIT.sql")
    @Sql(executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD,
            value = "/scripts/controller/registrar/registrar_department_rest_controller/getAllDepartmentsAndDoctorsIT_clear.sql")
    public void getAllDepartmentsAndDoctorsIT() throws Exception {
        accessToken = tokenUtil.obtainNewAccessToken("registrar@mail.com", "1", mockMvc);

        mockMvc.perform(
                        get("/api/registrar/department/get/all/with/doctors")
                                .header("Authorization", accessToken)
                                .contentType(MediaType.APPLICATION_JSON)
                )
                .andExpect(status().isOk())
//                .andDo(mvcResult -> System.out.println(mvcResult.getResponse().getContentAsString()))
                .andExpect(jsonPath("$.data.length()", Is.is(4)))
                .andExpect(jsonPath("$.data[0].id", Is.is(12)))
                .andExpect(jsonPath("$.data[0].name", Is.is("Первое детское отделение")))
                .andExpect(jsonPath("$.data[0].ageType", Is.is("CHILD")))
                .andExpect(jsonPath("$.data[0].chiefDoctorFirstName", Is.is("doctor30")))
                .andExpect(jsonPath("$.data[0].chiefDoctorLastName", Is.is("doctor30")))
                .andExpect(jsonPath("$.data[0].chiefContacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[0].chiefContacts[0].id", Is.is(1)))
                .andExpect(jsonPath("$.data[0].chiefContacts[0].contactType", Is.is("TELEGRAM")))
                .andExpect(jsonPath("$.data[0].chiefContacts[0].value", Is.is("13")))
                .andExpect(jsonPath("$.data[0].chiefContacts[1].id", Is.is(2)))
                .andExpect(jsonPath("$.data[0].chiefContacts[1].contactType", Is.is("PHONE")))
                .andExpect(jsonPath("$.data[0].chiefContacts[1].value", Is.is("23")))
                .andExpect(jsonPath("$.data[0].doctors.length()", Is.is(3)))
                .andExpect(jsonPath("$.data[0].doctors[0].id", Is.is(30)))
                .andExpect(jsonPath("$.data[0].doctors[0].lastName", Is.is("doctor30")))
                .andExpect(jsonPath("$.data[0].doctors[0].firstName", Is.is("doctor30")))
                .andExpect(jsonPath("$.data[0].doctors[0].patronymic", Is.is("doctor30")))
                .andExpect(jsonPath("$.data[0].doctors[0].gender", Is.is("MALE")))
                .andExpect(jsonPath("$.data[0].doctors[0].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[0].doctors[1].id", Is.is(40)))
                .andExpect(jsonPath("$.data[0].doctors[1].lastName", Is.is("doctor40")))
                .andExpect(jsonPath("$.data[0].doctors[1].firstName", Is.is("doctor40")))
                .andExpect(jsonPath("$.data[0].doctors[1].patronymic", Is.is("doctor40")))
                .andExpect(jsonPath("$.data[0].doctors[1].gender", Is.is("MALE")))
                .andExpect(jsonPath("$.data[0].doctors[1].contacts.length()", Is.is(1)))
                .andExpect(jsonPath("$.data[0].doctors[2].id", Is.is(50)))
                .andExpect(jsonPath("$.data[0].doctors[2].lastName", Is.is("doctor50")))
                .andExpect(jsonPath("$.data[0].doctors[2].firstName", Is.is("doctor50")))
                .andExpect(jsonPath("$.data[0].doctors[2].patronymic", Is.is("doctor50")))
                .andExpect(jsonPath("$.data[0].doctors[2].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[0].doctors[2].contacts.length()", Is.is(1)))

                .andExpect(jsonPath("$.data[1].id", Is.is(13)))
                .andExpect(jsonPath("$.data[1].name", Is.is("Второе детское отделение")))
                .andExpect(jsonPath("$.data[1].ageType", Is.is("CHILD")))
                .andExpect(jsonPath("$.data[1].chiefDoctorFirstName", Is.is("doctor60")))
                .andExpect(jsonPath("$.data[1].chiefDoctorLastName", Is.is("doctor60")))
                .andExpect(jsonPath("$.data[1].chiefContacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[1].chiefContacts[0].id", Is.is(5)))
                .andExpect(jsonPath("$.data[1].chiefContacts[0].contactType", Is.is("TELEGRAM")))
                .andExpect(jsonPath("$.data[1].chiefContacts[0].value", Is.is("56")))
                .andExpect(jsonPath("$.data[1].chiefContacts[1].id", Is.is(6)))
                .andExpect(jsonPath("$.data[1].chiefContacts[1].contactType", Is.is("PHONE")))
                .andExpect(jsonPath("$.data[1].chiefContacts[1].value", Is.is("66")))
                .andExpect(jsonPath("$.data[1].doctors.length()", Is.is(3)))
                .andExpect(jsonPath("$.data[1].doctors[0].id", Is.is(60)))
                .andExpect(jsonPath("$.data[1].doctors[0].lastName", Is.is("doctor60")))
                .andExpect(jsonPath("$.data[1].doctors[0].firstName", Is.is("doctor60")))
                .andExpect(jsonPath("$.data[1].doctors[0].patronymic", Is.is("doctor60")))
                .andExpect(jsonPath("$.data[1].doctors[0].gender", Is.is("MALE")))
                .andExpect(jsonPath("$.data[1].doctors[0].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[1].doctors[1].id", Is.is(70)))
                .andExpect(jsonPath("$.data[1].doctors[1].lastName", Is.is("doctor70")))
                .andExpect(jsonPath("$.data[1].doctors[1].firstName", Is.is("doctor70")))
                .andExpect(jsonPath("$.data[1].doctors[1].patronymic", Is.is("doctor70")))
                .andExpect(jsonPath("$.data[1].doctors[1].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[1].doctors[1].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[1].doctors[2].id", Is.is(80)))
                .andExpect(jsonPath("$.data[1].doctors[2].lastName", Is.is("doctor80")))
                .andExpect(jsonPath("$.data[1].doctors[2].firstName", Is.is("doctor80")))
                .andExpect(jsonPath("$.data[1].doctors[2].patronymic", Is.is("doctor80")))
                .andExpect(jsonPath("$.data[1].doctors[2].gender", Is.is("MALE")))
                .andExpect(jsonPath("$.data[1].doctors[2].contacts.length()", Is.is(0)))

                .andExpect(jsonPath("$.data[2].id", Is.is(14)))
                .andExpect(jsonPath("$.data[2].name", Is.is("Первое взрослое отделение")))
                .andExpect(jsonPath("$.data[2].ageType", Is.is("ADULT")))
                .andExpect(jsonPath("$.data[2].chiefDoctorFirstName", Is.is("doctor90")))
                .andExpect(jsonPath("$.data[2].chiefDoctorLastName", Is.is("doctor90")))
                .andExpect(jsonPath("$.data[2].chiefContacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[2].chiefContacts[0].id", Is.is(11)))
                .andExpect(jsonPath("$.data[2].chiefContacts[0].contactType", Is.is("TELEGRAM")))
                .andExpect(jsonPath("$.data[2].chiefContacts[0].value", Is.is("119")))
                .andExpect(jsonPath("$.data[2].chiefContacts[1].id", Is.is(13)))
                .andExpect(jsonPath("$.data[2].chiefContacts[1].contactType", Is.is("PHONE")))
                .andExpect(jsonPath("$.data[2].chiefContacts[1].value", Is.is("139")))
                .andExpect(jsonPath("$.data[2].doctors.length()", Is.is(3)))
                .andExpect(jsonPath("$.data[2].doctors[0].id", Is.is(90)))
                .andExpect(jsonPath("$.data[2].doctors[0].lastName", Is.is("doctor90")))
                .andExpect(jsonPath("$.data[2].doctors[0].firstName", Is.is("doctor90")))
                .andExpect(jsonPath("$.data[2].doctors[0].patronymic", Is.is("doctor90")))
                .andExpect(jsonPath("$.data[2].doctors[0].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[2].doctors[0].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[2].doctors[1].id", Is.is(100)))
                .andExpect(jsonPath("$.data[2].doctors[1].lastName", Is.is("doctor100")))
                .andExpect(jsonPath("$.data[2].doctors[1].firstName", Is.is("doctor100")))
                .andExpect(jsonPath("$.data[2].doctors[1].patronymic", Is.is("doctor100")))
                .andExpect(jsonPath("$.data[2].doctors[1].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[2].doctors[1].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[2].doctors[2].id", Is.is(110)))
                .andExpect(jsonPath("$.data[2].doctors[2].lastName", Is.is("doctor110")))
                .andExpect(jsonPath("$.data[2].doctors[2].firstName", Is.is("doctor110")))
                .andExpect(jsonPath("$.data[2].doctors[2].patronymic", Is.is("doctor110")))
                .andExpect(jsonPath("$.data[2].doctors[2].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[2].doctors[2].contacts.length()", Is.is(2)))

                .andExpect(jsonPath("$.data[3].id", Is.is(15)))
                .andExpect(jsonPath("$.data[3].name", Is.is("Второе взрослое отделение")))
                .andExpect(jsonPath("$.data[3].ageType", Is.is("ADULT")))
                .andExpect(jsonPath("$.data[3].chiefDoctorFirstName", Matchers.nullValue()))
                .andExpect(jsonPath("$.data[3].chiefDoctorLastName", Matchers.nullValue()))
                .andExpect(jsonPath("$.data[3].chiefContacts", Matchers.nullValue()))
                .andExpect(jsonPath("$.data[3].doctors.length()", Is.is(3)))
                .andExpect(jsonPath("$.data[3].doctors[0].id", Is.is(120)))
                .andExpect(jsonPath("$.data[3].doctors[0].lastName", Is.is("doctor120")))
                .andExpect(jsonPath("$.data[3].doctors[0].firstName", Is.is("doctor120")))
                .andExpect(jsonPath("$.data[3].doctors[0].patronymic", Is.is("doctor120")))
                .andExpect(jsonPath("$.data[3].doctors[0].gender", Is.is("MALE")))
                .andExpect(jsonPath("$.data[3].doctors[0].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[3].doctors[1].id", Is.is(130)))
                .andExpect(jsonPath("$.data[3].doctors[1].lastName", Is.is("doctor130")))
                .andExpect(jsonPath("$.data[3].doctors[1].firstName", Is.is("doctor130")))
                .andExpect(jsonPath("$.data[3].doctors[1].patronymic", Is.is("doctor130")))
                .andExpect(jsonPath("$.data[3].doctors[1].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[3].doctors[1].contacts.length()", Is.is(2)))
                .andExpect(jsonPath("$.data[3].doctors[2].id", Is.is(140)))
                .andExpect(jsonPath("$.data[3].doctors[2].lastName", Is.is("doctor140")))
                .andExpect(jsonPath("$.data[3].doctors[2].firstName", Is.is("doctor140")))
                .andExpect(jsonPath("$.data[3].doctors[2].patronymic", Is.is("doctor140")))
                .andExpect(jsonPath("$.data[3].doctors[2].gender", Is.is("FEMALE")))
                .andExpect(jsonPath("$.data[3].doctors[2].contacts.length()", Is.is(2)));
    }
}
