TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE medical_organization CASCADE;
TRUNCATE TABLE department CASCADE;
TRUNCATE TABLE employee_history CASCADE;
TRUNCATE TABLE user_history CASCADE;
TRUNCATE TABLE contact CASCADE;