TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE medical_organization CASCADE;
TRUNCATE TABLE department CASCADE;
TRUNCATE TABLE building CASCADE;
TRUNCATE TABLE cabinet CASCADE;
TRUNCATE TABLE position CASCADE;