TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE university CASCADE;
TRUNCATE TABLE diploma CASCADE;
TRUNCATE TABLE labor_contract CASCADE;
TRUNCATE TABLE attestation CASCADE;
TRUNCATE TABLE medical_organization CASCADE;
TRUNCATE TABLE department CASCADE;
TRUNCATE TABLE building CASCADE;
TRUNCATE TABLE cabinet CASCADE;
TRUNCATE TABLE employee_history CASCADE;
TRUNCATE TABLE position CASCADE;
TRUNCATE TABLE wage CASCADE;

