TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE polis CASCADE;
TRUNCATE TABLE identity_document CASCADE;
TRUNCATE TABLE patient_history CASCADE;
TRUNCATE TABLE user_history CASCADE;
TRUNCATE TABLE smo CASCADE;
TRUNCATE TABLE invite CASCADE;