CREATE TABLE appeal
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    closed_date        date,
    is_ready           BOOLEAN                                 NOT NULL,
    order_id           BIGINT,
    patient_history_id BIGINT                                  NOT NULL,
    disease_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_appeal PRIMARY KEY (id)
);

CREATE TABLE attestation
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_from         date                                    NOT NULL,
    date_to           date                                    NOT NULL,
    number            VARCHAR(255)                            NOT NULL,
    university_id     BIGINT                                  NOT NULL,
    labor_contract_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_attestation PRIMARY KEY (id)
);

CREATE TABLE bank
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    legal_address VARCHAR(255)                            NOT NULL,
    bik           VARCHAR(255)                            NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date,
    CONSTRAINT pk_bank PRIMARY KEY (id)
);

CREATE TABLE bank_account
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype                   VARCHAR(31),
    name                    VARCHAR(255),
    number                  VARCHAR(255)                            NOT NULL,
    is_disabled             BOOLEAN                                 NOT NULL,
    bank_id                 BIGINT                                  NOT NULL,
    smo_id                  BIGINT,
    medical_organization_id BIGINT,
    employee_history_id     BIGINT,
    CONSTRAINT pk_bank_account PRIMARY KEY (id)
);

CREATE TABLE building
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    physical_address        VARCHAR(255)                            NOT NULL,
    medical_organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_building PRIMARY KEY (id)
);

CREATE TABLE cabinet
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number      INTEGER                                 NOT NULL,
    name        VARCHAR(255),
    building_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cabinet PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contact_type    VARCHAR(255)                            NOT NULL,
    value           VARCHAR(255)                            NOT NULL,
    user_history_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE department
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    age_type                VARCHAR(255),
    chief_doctor_id         BIGINT,
    io_chief_doctor_id      BIGINT,
    medical_organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE diploma
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number VARCHAR(255)                            NOT NULL,
    end_date      date                                    NOT NULL,
    university_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_diploma PRIMARY KEY (id)
);

CREATE TABLE disease
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier    VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    is_disabled   BOOLEAN                                 NOT NULL,
    age_type      VARCHAR(255),
    department_id BIGINT,
    CONSTRAINT pk_disease PRIMARY KEY (id)
);

CREATE TABLE employee_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype         VARCHAR(31),
    is_public     BOOLEAN                                 NOT NULL,
    employee_id   BIGINT                                  NOT NULL,
    department_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_employeehistory PRIMARY KEY (id)
);

CREATE TABLE equipment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    inventory_number  VARCHAR(255)                            NOT NULL,
    price             NUMERIC(8,2)                            NOT NULL,
    purchase_date     date                                    NOT NULL,
    installation_date date,
    disposal_date     date,
    position_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipment PRIMARY KEY (id)
);

CREATE TABLE event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type        VARCHAR(255)                            NOT NULL,
    event_level       VARCHAR(255)                            NOT NULL,
    serial_number     VARCHAR(255)                            NOT NULL,
    date              date                                    NOT NULL,
    value             VARCHAR(255)                            NOT NULL,
    labor_contract_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE identity_document
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type   VARCHAR(255)                            NOT NULL,
    serial          VARCHAR(255)                            NOT NULL,
    number          VARCHAR(255)                            NOT NULL,
    date_start      date                                    NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    patronymic      VARCHAR(255),
    birthday        date                                    NOT NULL,
    gender          VARCHAR(255)                            NOT NULL,
    is_deprecated   BOOLEAN                                 NOT NULL,
    user_history_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_identity_document PRIMARY KEY (id)
);

CREATE TABLE invite
(
    email           VARCHAR(255)                NOT NULL,
    token           VARCHAR(255)                NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_invite PRIMARY KEY (email)
);

CREATE TABLE labor_contract
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date          date                                    NOT NULL,
    end_date            date,
    part                NUMERIC(8,2)                            NOT NULL,
    employee_history_id BIGINT                                  NOT NULL,
    position_id         BIGINT                                  NOT NULL,
    diploma_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_labor_contract PRIMARY KEY (id)
);

CREATE TABLE license
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    number                  VARCHAR(255)                            NOT NULL,
    date_from               date                                    NOT NULL,
    date_to                 date                                    NOT NULL,
    medical_organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_license PRIMARY KEY (id)
);

CREATE TABLE medical_organization
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                         VARCHAR(255)                            NOT NULL,
    name                         VARCHAR(255)                            NOT NULL,
    legal_address                VARCHAR(255),
    ogrn                         VARCHAR(255)                            NOT NULL,
    start_date                   date                                    NOT NULL,
    end_date                     date,
    full_employment_status_range NUMERIC(8,2)                            NOT NULL,
    director_id                  BIGINT,
    io_director_id               BIGINT,
    CONSTRAINT pk_medical_organization PRIMARY KEY (id)
);

CREATE TABLE medical_service
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier    VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    is_disabled   BOOLEAN                                 NOT NULL,
    department_id BIGINT,
    CONSTRAINT pk_medical_service PRIMARY KEY (id)
);

CREATE TABLE municipal_order
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    money                   NUMERIC(8,2)                            NOT NULL,
    period                  date                                    NOT NULL,
    medical_organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_municipal_order PRIMARY KEY (id)
);

CREATE TABLE municipal_order_for_smo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    money              NUMERIC(8,2)                            NOT NULL,
    municipal_order_id BIGINT                                  NOT NULL,
    smo_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_municipal_order_for_smo PRIMARY KEY (id)
);

CREATE TABLE municipal_order_for_smo_on_month
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    month                      VARCHAR(255)                            NOT NULL,
    money                      NUMERIC(8,2)                            NOT NULL,
    municipal_order_for_smo_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_municipal_order_for_smo_on_month PRIMARY KEY (id)
);

CREATE TABLE oms_price_of_medical_service
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_from           date                                    NOT NULL,
    day_to             date,
    yet                NUMERIC(8,2)                            NOT NULL,
    medical_service_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_oms_price_of_medical_service PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    insurance_type          VARCHAR(255)                            NOT NULL,
    comment                 VARCHAR(255),
    date                    date                                    NOT NULL,
    money                   NUMERIC(8,2),
    is_formed               BOOLEAN                                 NOT NULL,
    is_accepted_for_payment BOOLEAN                                 NOT NULL,
    is_payed                BOOLEAN                                 NOT NULL,
    medical_organization_id BIGINT                                  NOT NULL,
    smo_id                  BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE patient_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_patienthistory PRIMARY KEY (id)
);

CREATE TABLE pay_price_of_medical_service
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_from           date                                    NOT NULL,
    day_to             date,
    money              NUMERIC(8,2)                            NOT NULL,
    medical_service_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_pay_price_of_medical_service PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_pay                  date                                    NOT NULL,
    money                     NUMERIC(8,2)                            NOT NULL,
    payer_bank_account_id     BIGINT                                  NOT NULL,
    recipient_bank_account_id BIGINT                                  NOT NULL,
    payment_status            VARCHAR(255)                            NOT NULL,
    comment                   VARCHAR(255),
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE polis
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    insurance_type     VARCHAR(255)                            NOT NULL,
    serial             VARCHAR(255),
    number             VARCHAR(255)                            NOT NULL,
    date_start         date                                    NOT NULL,
    date_end           date                                    NOT NULL,
    smo_id             BIGINT                                  NOT NULL,
    is_deprecated      BOOLEAN                                 NOT NULL,
    patient_history_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_polis PRIMARY KEY (id)
);

CREATE TABLE position
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    days_for_vocation INTEGER                                 NOT NULL,
    department_id     BIGINT                                  NOT NULL,
    cabinet_id        BIGINT,
    CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE salary
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_from           date                                    NOT NULL,
    date_to             date                                    NOT NULL,
    labor_contract_pay  NUMERIC(8,2),
    vacation_pay        NUMERIC(8,2),
    bonus_pay           NUMERIC(8,2),
    employee_history_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_salary PRIMARY KEY (id)
);

CREATE TABLE smo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    region     VARCHAR(255)                            NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date,
    CONSTRAINT pk_smo PRIMARY KEY (id)
);

CREATE TABLE talon
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    patient_history_id BIGINT,
    doctor_history_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_talon PRIMARY KEY (id)
);

CREATE TABLE university
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_university PRIMARY KEY (id)
);

CREATE TABLE user_history
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_userhistory PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype      VARCHAR(31),
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    snils      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    patronymic VARCHAR(255),
    birthday   date                                    NOT NULL,
    gender     VARCHAR(255)                            NOT NULL,
    role_id    BIGINT,
    is_enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vacation
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_from         date                                    NOT NULL,
    date_to           date                                    NOT NULL,
    vocation_type     VARCHAR(255)                            NOT NULL,
    comment           VARCHAR(255),
    labor_contract_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_vacation PRIMARY KEY (id)
);

CREATE TABLE visit
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_visit      date                                    NOT NULL,
    doctor_history_id BIGINT                                  NOT NULL,
    appeal_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_visit PRIMARY KEY (id)
);

CREATE TABLE visit_medical_services
(
    medical_service_id BIGINT NOT NULL,
    visit_id           BIGINT NOT NULL
);

CREATE TABLE wage
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_start  date                                    NOT NULL,
    date_end    date,
    value       DECIMAL                                 NOT NULL,
    position_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_wage PRIMARY KEY (id)
);

CREATE TABLE yet
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price                   NUMERIC(8,2)                            NOT NULL,
    day_from                date                                    NOT NULL,
    day_to                  date,
    medical_organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_yet PRIMARY KEY (id)
);

ALTER TABLE attestation
    ADD CONSTRAINT uc_attestation_number UNIQUE (number);

ALTER TABLE bank_account
    ADD CONSTRAINT uc_bank_account_number UNIQUE (number);

ALTER TABLE disease
    ADD CONSTRAINT uc_disease_identifier UNIQUE (identifier);

ALTER TABLE equipment
    ADD CONSTRAINT uc_equipment_inventory_number UNIQUE (inventory_number);

ALTER TABLE event
    ADD CONSTRAINT uc_event_serial_number UNIQUE (serial_number);

ALTER TABLE invite
    ADD CONSTRAINT uc_invite_token UNIQUE (token);

ALTER TABLE medical_organization
    ADD CONSTRAINT uc_medical_organization_code UNIQUE (code);

ALTER TABLE medical_organization
    ADD CONSTRAINT uc_medical_organization_ogrn UNIQUE (ogrn);

ALTER TABLE medical_service
    ADD CONSTRAINT uc_medical_service_identifier UNIQUE (identifier);

ALTER TABLE position
    ADD CONSTRAINT uc_position_name UNIQUE (name);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE appeal
    ADD CONSTRAINT FK_APPEAL_ON_DISEASE FOREIGN KEY (disease_id) REFERENCES disease (id);

ALTER TABLE appeal
    ADD CONSTRAINT FK_APPEAL_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE appeal
    ADD CONSTRAINT FK_APPEAL_ON_PATIENT_HISTORY FOREIGN KEY (patient_history_id) REFERENCES patient_history (id);

ALTER TABLE attestation
    ADD CONSTRAINT FK_ATTESTATION_ON_LABOR_CONTRACT FOREIGN KEY (labor_contract_id) REFERENCES labor_contract (id);

ALTER TABLE attestation
    ADD CONSTRAINT FK_ATTESTATION_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES university (id);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_BANK FOREIGN KEY (bank_id) REFERENCES bank (id);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_EMPLOYEE_HISTORY FOREIGN KEY (employee_history_id) REFERENCES employee_history (id);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_SMO FOREIGN KEY (smo_id) REFERENCES smo (id);

ALTER TABLE building
    ADD CONSTRAINT FK_BUILDING_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE cabinet
    ADD CONSTRAINT FK_CABINET_ON_BUILDING FOREIGN KEY (building_id) REFERENCES building (id);

ALTER TABLE contact
    ADD CONSTRAINT FK_CONTACT_ON_USER_HISTORY FOREIGN KEY (user_history_id) REFERENCES user_history (id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_CHIEF_DOCTOR FOREIGN KEY (chief_doctor_id) REFERENCES users (id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_IO_CHIEF_DOCTOR FOREIGN KEY (io_chief_doctor_id) REFERENCES users (id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE diploma
    ADD CONSTRAINT FK_DIPLOMA_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES university (id);

ALTER TABLE disease
    ADD CONSTRAINT FK_DISEASE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE employee_history
    ADD CONSTRAINT FK_EMPLOYEEHISTORY_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE employee_history
    ADD CONSTRAINT FK_EMPLOYEEHISTORY_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES users (id);

ALTER TABLE equipment
    ADD CONSTRAINT FK_EQUIPMENT_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_LABOR_CONTRACT FOREIGN KEY (labor_contract_id) REFERENCES labor_contract (id);

ALTER TABLE identity_document
    ADD CONSTRAINT FK_IDENTITY_DOCUMENT_ON_USER_HISTORY FOREIGN KEY (user_history_id) REFERENCES user_history (id);

ALTER TABLE labor_contract
    ADD CONSTRAINT FK_LABOR_CONTRACT_ON_DIPLOMA FOREIGN KEY (diploma_id) REFERENCES diploma (id);

ALTER TABLE labor_contract
    ADD CONSTRAINT FK_LABOR_CONTRACT_ON_EMPLOYEE_HISTORY FOREIGN KEY (employee_history_id) REFERENCES employee_history (id);

ALTER TABLE labor_contract
    ADD CONSTRAINT FK_LABOR_CONTRACT_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE license
    ADD CONSTRAINT FK_LICENSE_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE medical_organization
    ADD CONSTRAINT FK_MEDICAL_ORGANIZATION_ON_DIRECTOR FOREIGN KEY (director_id) REFERENCES users (id);

ALTER TABLE medical_organization
    ADD CONSTRAINT FK_MEDICAL_ORGANIZATION_ON_IO_DIRECTOR FOREIGN KEY (io_director_id) REFERENCES users (id);

ALTER TABLE medical_service
    ADD CONSTRAINT FK_MEDICAL_SERVICE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE municipal_order_for_smo_on_month
    ADD CONSTRAINT FK_MUNICIPAL_ORDER_FOR_SMO_ON_MONTH_ON_MUNICIPAL_ORDER_FOR_SMO FOREIGN KEY (municipal_order_for_smo_id) REFERENCES municipal_order_for_smo (id);

ALTER TABLE municipal_order_for_smo
    ADD CONSTRAINT FK_MUNICIPAL_ORDER_FOR_SMO_ON_MUNICIPAL_ORDER FOREIGN KEY (municipal_order_id) REFERENCES municipal_order (id);

ALTER TABLE municipal_order_for_smo
    ADD CONSTRAINT FK_MUNICIPAL_ORDER_FOR_SMO_ON_SMO FOREIGN KEY (smo_id) REFERENCES smo (id);

ALTER TABLE municipal_order
    ADD CONSTRAINT FK_MUNICIPAL_ORDER_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE oms_price_of_medical_service
    ADD CONSTRAINT FK_OMS_PRICE_OF_MEDICAL_SERVICE_ON_MEDICAL_SERVICE FOREIGN KEY (medical_service_id) REFERENCES medical_service (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SMO FOREIGN KEY (smo_id) REFERENCES smo (id);

ALTER TABLE patient_history
    ADD CONSTRAINT FK_PATIENTHISTORY_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES users (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_PAYER_BANK_ACCOUNT FOREIGN KEY (payer_bank_account_id) REFERENCES bank_account (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_RECIPIENT_BANK_ACCOUNT FOREIGN KEY (recipient_bank_account_id) REFERENCES bank_account (id);

ALTER TABLE pay_price_of_medical_service
    ADD CONSTRAINT FK_PAY_PRICE_OF_MEDICAL_SERVICE_ON_MEDICAL_SERVICE FOREIGN KEY (medical_service_id) REFERENCES medical_service (id);

ALTER TABLE polis
    ADD CONSTRAINT FK_POLIS_ON_PATIENT_HISTORY FOREIGN KEY (patient_history_id) REFERENCES patient_history (id);

ALTER TABLE polis
    ADD CONSTRAINT FK_POLIS_ON_SMO FOREIGN KEY (smo_id) REFERENCES smo (id);

ALTER TABLE position
    ADD CONSTRAINT FK_POSITION_ON_CABINET FOREIGN KEY (cabinet_id) REFERENCES cabinet (id);

ALTER TABLE position
    ADD CONSTRAINT FK_POSITION_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE salary
    ADD CONSTRAINT FK_SALARY_ON_EMPLOYEE_HISTORY FOREIGN KEY (employee_history_id) REFERENCES employee_history (id);

ALTER TABLE talon
    ADD CONSTRAINT FK_TALON_ON_DOCTOR_HISTORY FOREIGN KEY (doctor_history_id) REFERENCES employee_history (id);

ALTER TABLE talon
    ADD CONSTRAINT FK_TALON_ON_PATIENT_HISTORY FOREIGN KEY (patient_history_id) REFERENCES patient_history (id);

ALTER TABLE user_history
    ADD CONSTRAINT FK_USERHISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE vacation
    ADD CONSTRAINT FK_VACATION_ON_LABOR_CONTRACT FOREIGN KEY (labor_contract_id) REFERENCES labor_contract (id);

ALTER TABLE visit
    ADD CONSTRAINT FK_VISIT_ON_APPEAL FOREIGN KEY (appeal_id) REFERENCES appeal (id);

ALTER TABLE visit
    ADD CONSTRAINT FK_VISIT_ON_DOCTOR_HISTORY FOREIGN KEY (doctor_history_id) REFERENCES employee_history (id);

ALTER TABLE wage
    ADD CONSTRAINT FK_WAGE_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE yet
    ADD CONSTRAINT FK_YET_ON_MEDICAL_ORGANIZATION FOREIGN KEY (medical_organization_id) REFERENCES medical_organization (id);

ALTER TABLE visit_medical_services
    ADD CONSTRAINT fk_vismedser_on_medical_service FOREIGN KEY (medical_service_id) REFERENCES medical_service (id);

ALTER TABLE visit_medical_services
    ADD CONSTRAINT fk_vismedser_on_visit FOREIGN KEY (visit_id) REFERENCES visit (id);